// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'rope.dart';

// These functions are ignored because they are not marked as `pub`: `contains_same_tag_closing`, `contains_same_tag_opening`, `extract_opening_tag_name`, `find_matching_bracket_in_rope`, `find_matching_closing_tag_line`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LineBlock`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `add_summary`, `add_summary`, `add_summary`, `add_summary`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `cmp`, `cmp`, `cmp`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `partial_cmp`, `partial_cmp`, `partial_cmp`, `summary`, `zero`, `zero`, `zero`, `zero`

Future<List<RustFoldRange>> foldsComputeAll({required RopeBridge rope}) =>
    RustLib.instance.api.crateApiEditorFoldsComputeAll(rope: rope);

PlatformInt64 foldsFindMatchingBracket({
  required RopeBridge rope,
  required int targetOffset,
}) => RustLib.instance.api.crateApiEditorFoldsFindMatchingBracket(
  rope: rope,
  targetOffset: targetOffset,
);

VisibleLineRange visibleLineRangeUnwrapped({
  required int totalLines,
  required double viewTop,
  required double viewBottom,
  required double lineHeight,
}) => RustLib.instance.api.crateApiEditorVisibleLineRangeUnwrapped(
  totalLines: totalLines,
  viewTop: viewTop,
  viewBottom: viewBottom,
  lineHeight: lineHeight,
);

ViewportFrame buildViewportFrame({
  required RopeBridge rope,
  required double viewTop,
  required double viewBottom,
  required double lineHeight,
}) => RustLib.instance.api.crateApiEditorBuildViewportFrame(
  rope: rope,
  viewTop: viewTop,
  viewBottom: viewBottom,
  lineHeight: lineHeight,
);

List<GuideBlock> guidesComputeViewport({
  required RopeBridge rope,
  required BigInt firstVisible,
  required BigInt lastVisible,
  required BigInt tabSize,
}) => RustLib.instance.api.crateApiEditorGuidesComputeViewport(
  rope: rope,
  firstVisible: firstVisible,
  lastVisible: lastVisible,
  tabSize: tabSize,
);

Future<List<String>> wordsExtract({required RopeBridge rope}) =>
    RustLib.instance.api.crateApiEditorWordsExtract(rope: rope);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LayoutMap>>
abstract class LayoutMap implements RustOpaqueInterface {
  ViewportFrame buildViewportFrame({
    required double viewTop,
    required double viewBottom,
    required double fallbackLineHeight,
  });

  void clear();

  void insertLine({
    required BigInt lineIdx,
    required BigInt lenChars,
    required double height,
    required bool isFolded,
  });

  BigInt lenLines();

  factory LayoutMap() => RustLib.instance.api.crateApiEditorLayoutMapNew();

  void pushLine({
    required BigInt lenChars,
    required double height,
    required bool isFolded,
  });

  void removeLine({required BigInt lineIdx});

  double totalHeight();

  void updateLine({
    required BigInt lineIdx,
    required BigInt lenChars,
    required double height,
    required bool isFolded,
  });

  VisibleLineRange visibleRangeByHeight({
    required double viewTop,
    required double viewBottom,
  });

  int visualLineFromCharOffset({required BigInt charOffset});
}

class CharOffset {
  final BigInt field0;

  const CharOffset({required this.field0});

  static Future<CharOffset> default_() =>
      RustLib.instance.api.crateApiEditorCharOffsetDefault();

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CharOffset &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

class GuideBlock {
  final int startLine;
  final int endLine;
  final int indentLevel;
  final int leadingSpaces;

  const GuideBlock({
    required this.startLine,
    required this.endLine,
    required this.indentLevel,
    required this.leadingSpaces,
  });

  @override
  int get hashCode =>
      startLine.hashCode ^
      endLine.hashCode ^
      indentLevel.hashCode ^
      leadingSpaces.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuideBlock &&
          runtimeType == other.runtimeType &&
          startLine == other.startLine &&
          endLine == other.endLine &&
          indentLevel == other.indentLevel &&
          leadingSpaces == other.leadingSpaces;
}

class LineCount {
  final BigInt field0;

  const LineCount({required this.field0});

  static Future<LineCount> default_() =>
      RustLib.instance.api.crateApiEditorLineCountDefault();

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LineCount &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

class LineSummary {
  final BigInt lenChars;
  final double height;
  final BigInt lines;

  const LineSummary({
    required this.lenChars,
    required this.height,
    required this.lines,
  });

  static Future<LineSummary> default_() =>
      RustLib.instance.api.crateApiEditorLineSummaryDefault();

  @override
  int get hashCode => lenChars.hashCode ^ height.hashCode ^ lines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LineSummary &&
          runtimeType == other.runtimeType &&
          lenChars == other.lenChars &&
          height == other.height &&
          lines == other.lines;
}

class PixelHeight {
  final double field0;

  const PixelHeight({required this.field0});

  static Future<PixelHeight> default_() =>
      RustLib.instance.api.crateApiEditorPixelHeightDefault();

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PixelHeight &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

class RustFoldRange {
  final int startLine;
  final int endLine;

  const RustFoldRange({required this.startLine, required this.endLine});

  @override
  int get hashCode => startLine.hashCode ^ endLine.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustFoldRange &&
          runtimeType == other.runtimeType &&
          startLine == other.startLine &&
          endLine == other.endLine;
}

class ViewportFrame {
  final int firstLine;
  final int lastLine;
  final double firstLineY;
  final List<LineSummary> lines;

  const ViewportFrame({
    required this.firstLine,
    required this.lastLine,
    required this.firstLineY,
    required this.lines,
  });

  @override
  int get hashCode =>
      firstLine.hashCode ^
      lastLine.hashCode ^
      firstLineY.hashCode ^
      lines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ViewportFrame &&
          runtimeType == other.runtimeType &&
          firstLine == other.firstLine &&
          lastLine == other.lastLine &&
          firstLineY == other.firstLineY &&
          lines == other.lines;
}

class VisibleLineRange {
  final int firstLine;
  final int lastLine;
  final double firstLineY;

  const VisibleLineRange({
    required this.firstLine,
    required this.lastLine,
    required this.firstLineY,
  });

  @override
  int get hashCode =>
      firstLine.hashCode ^ lastLine.hashCode ^ firstLineY.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VisibleLineRange &&
          runtimeType == other.runtimeType &&
          firstLine == other.firstLine &&
          lastLine == other.lastLine &&
          firstLineY == other.firstLineY;
}
