// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `compute_bidi_segments`, `direction_for_char`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RopeBridge>>
abstract class RopeBridge implements RustOpaqueInterface {
  List<String> cachedLines();

  List<String> cachedLinesRange({
    required BigInt startLine,
    required BigInt endLine,
  });

  String charAt({required BigInt position});

  BigInt charToLine({required BigInt charIdx});

  RopeBridge copy();

  static RopeBridge create({required String initialText}) => RustLib
      .instance
      .api
      .crateApiRopeRopeBridgeCreate(initialText: initialText);

  RopeBridge deepClone();

  BigInt findLineEnd({required BigInt offset});

  BigInt findLineStart({required BigInt offset});

  List<BiDiSegment> getBidiSegmentsForLine({required BigInt lineIndex});

  List<BiDiSegment> getBidiSegmentsInRange({
    required BigInt start,
    required BigInt end,
  });

  String getText();

  void insert({required BigInt charIdx, required String text});

  BigInt lenChars();

  BigInt lenLines();

  String line({required BigInt lineIdx});

  BigInt lineToChar({required BigInt lineIdx});

  TextDirection primaryDirection();

  void remove({required BigInt start, required BigInt end});

  SelectionState replaceRangeAndUpdateSelection({
    required BigInt start,
    required BigInt end,
    required String replacement,
    required bool preserveOldCursor,
    required BigInt oldBase,
    required BigInt oldExtent,
  });

  SelectionState selection();

  void setSelection({required BigInt baseOffset, required BigInt extentOffset});

  String slice({required BigInt start, required BigInt end});

  TextDirection textDirection();
}

class BiDiSegment {
  final BigInt start;
  final BigInt end;
  final TextDirection direction;

  const BiDiSegment({
    required this.start,
    required this.end,
    required this.direction,
  });

  @override
  int get hashCode => start.hashCode ^ end.hashCode ^ direction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BiDiSegment &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end &&
          direction == other.direction;
}

class SelectionState {
  final BigInt baseOffset;
  final BigInt extentOffset;

  const SelectionState({required this.baseOffset, required this.extentOffset});

  @override
  int get hashCode => baseOffset.hashCode ^ extentOffset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SelectionState &&
          runtimeType == other.runtimeType &&
          baseOffset == other.baseOffset &&
          extentOffset == other.extentOffset;
}

enum TextDirection { ltr, rtl, mixed }
